#!/usr/bin/python 

a=[]
for i in range(0,20):
	a.append(0)
def jump(n,m,i):
'''	if m==1:
		a[i]=1
		if a[i]!=a[i-1]:
			print a[0:i+1]
		return '''
	if m==0:
#		if a[i-2]!=a[i-1]:
		print a[0:i]
		return
	else:
		if n>m:
			j=m
		else:
			j=n
		while j*(j+1)>=m/2:
			a[i]=j
			jump(j-1,m-j,i+1)
			j=j-1
		
jump(30,40,0)
print a[0]
print "success"
